services:
  app:
    image: golang:1.21
    container_name: ecommerce-go-app
    working_dir: /app
    volumes:
      - ./:/app
    command: go run main.go
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: ecommerce-go-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecommerce
      MONGO_INITDB_ROOT_PASSWORD: ecommercepass
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: